name: user_agent
description: A Dart user agent detection library.
version: 2.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/user_agent
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.0.0
